---
title: "Suçlu Profilleri"
author: 
  - Nevcihan Gün[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 19080217, [Github Repo](https://github.com/nevcihangun1643/arasinav.git)


# Giriş
Suç ne demektir. TDK’ye göre toplumsal düzeni hukuki boyutta bilerek veya bilmeyerek bozan kişilerin yaptığı eylemdir. Ancak olayların içine girdiğimizde kavramlar bu kadar kolay açıklanamıyor. Kişiler ve suç dereceleri devamlı artış göstermektedir. Küçük suçlar sinsilesi belirli oranda suç düzeyini arttırmaktadır. Herhangi bir olay mahallini araştıran polisler suçluya mağdurdan ulaşırlar. Mağdurun yaşı, cinsiyeti, medeni hali gibi özellikler bize suçlunun yaşı, cinsiyeti medeni hali gibi özelliklerini öğrenmemiz için ipucu verir. Suçlu profilinde organize olan ve olmayan suçlular vardır. Organize suçlu profilinde genelde suçlu mağdur bile benzer hayat şartlarına. Yüksek eğitim düzeyine ve hatta yüksek sosyal çevreye sabit olabilmektedir. Organize olmayan profilde ise zıt yönde bir ilişki vardır. Mağdurun tek ilişkisi yanlış zamanda yanlış yerde olmasıdır.  @canturk2004succlu

## Çalışmanın Amacı
Araştırmamdaki temel amaç sayılarla problemlerin nerede olduğunun tespitini yapmaktır.Problem ne ve hangi konuda ciddileşiyor sayılarla bir nebze görebiliriz.@kubra2020succa @namal2021eski @agnew2006pressured 

## Literatür 
Bireyler küçük veya büyük bir kez suç işlediklerinde toplumdan dışlanırlar. Damgalanırlar ve bu süreç onu takip eder. Sadece hukuki düzeyde de değil pek çok işyerlerinde çalışanlar bazı olaylar neticesinde uyumsuz olarak damgalanabilir. Bireyler önce itiraz edip uyum sağlama eğiliminde olsalar da zaman geçtikçe duruma uyum sağlarlar. Bu benzeri bir durum yaşayan bir bireye yöneltilen soru neticesinde “Bu duruma artık alıştım, insanların beni nasıl göreceği umurumda değil.” Cevabını vermiştir. Bu cevaptan anlayabileceğimiz üzere dışlanan birey belli bir noktadan sonra mevzubahis konuyu kabullenip bunu karakterine işliyor ve büyük bir oranda kendini böyle kabul eden birey suçun düzeyini arttırmaya da devam edecektir. Bu olay dışında ise kimi bireyler de dışlanma yaşamadıklarını tam tersi onaylama aldıklarını dile getirmişlerdir. Bir mahkûm bunu şu şekilde açıklıyor. “Cezaevinden çıktığımda herhangi bir dışlanmaya maruz kalmadım. Hatta çevremdekiler bana keşke öldürseydin o namussuzu dediler. Hem hâkimlerde bizden yana. Onlar bile indirimli ceza veriyor bizlere.” Bu cümleden de anladığımız kadarıyla dışlanma bile yaşadığımız şehrin kültürünü barındırıyor. Peki sonuç nasıl değişecek. Benim kanımca sonuç değişmeyecek çünkü bir durumda birey toplumun ona yüklediğini kabul ederken diğerinde ise yaptığı onaylamayla kendi karakterini bu şekilde oluşturmayı seçiyor.@yavuzer2013crime 

\newpage
# Kaynakça {#references}
<div id="refs"></div>

